[package]
name = "rust_launcher_utils"
version = "0.0.3"
edition = "2021"

[dependencies]
fuzzy-matcher = "0.3.7"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
rink-core = { version = "0.8.0", features = ["bundle-files"] }
serde_json = "1.0.133"
